data:extend({
	{
		name = "tral-show-button",
		setting_type = "runtime-per-user",
		type = "bool-setting",
		default_value = true,
	},
  {
		name = "tral-refresh-interval",
		setting_type = "runtime-global",
		type = "int-setting",
		default_value = 120,
		minimum_value = 60,
		maximum_value = 600,
	},
	{
		name = "tral-debug-level",
    setting_type = "runtime-global",
		type = "bool-setting",
    default_value = false,
	},
  {
		name = "tral-station-timeout",
		setting_type = "runtime-global",
		type = "int-setting",
		default_value = 60,
		minimum_value = -1,
		maximum_value = 3600,
	},
  {
		name = "tral-signal-timeout",
		setting_type = "runtime-global",
		type = "int-setting",
		default_value = 60,
		minimum_value = -1,
		maximum_value = 3600,
	},
  {
		name = "tral-no-path-timeout",
		setting_type = "runtime-global",
		type = "int-setting",
		default_value = 0,
		minimum_value = -1,
		maximum_value = 3600,
	},
  {
		name = "tral-no-schedule-timeout",
		setting_type = "runtime-global",
		type = "int-setting",
		default_value = 60,
		minimum_value = -1,
		maximum_value = 3600,
	},
  {
		name = "tral-manual-timeout",
		setting_type = "runtime-global",
		type = "int-setting",
		default_value = -1,
		minimum_value = -1,
		maximum_value = 3600,
	},
})